wandb_version: 1

bagging_fraction:
  desc: null
  value: 0.9898220410240036
bagging_freq:
  desc: null
  value: 12
feature_fraction:
  desc: null
  value: 0.4435657189828228
lambda_l1:
  desc: null
  value: 6.3846838107282275
lambda_l2:
  desc: null
  value: 3.774511311359523
learning_rate:
  desc: null
  value: 0.2964307680282641
max_depth:
  desc: null
  value: 41
min_data_in_leaf:
  desc: null
  value: 101
num_leaves:
  desc: null
  value: 35
ratio:
  desc: null
  value: 0.28269731708950635
project:
  desc: null
  value: lightgbm-sweep
method:
  desc: null
  value: bayes
metric:
  desc: null
  value:
    name: auc
    goal: maximize
parameters:
  desc: null
  value:
    num_leaves:
      min: 20
      max: 60
    learning_rate:
      min: 0.01
      max: 0.4
    min_data_in_leaf:
      min: 5
      max: 120
    feature_fraction:
      min: 0.3
      max: 1.0
    bagging_fraction:
      min: 0.7
      max: 1.0
    bagging_freq:
      min: 5
      max: 20
    lambda_l1:
      min: 0.0
      max: 10.0
    lambda_l2:
      min: 0.0
      max: 15.0
    max_depth:
      min: 10
      max: 50
    ratio:
      min: 0.05
      max: 0.3
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.2
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706148514.904471
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 25
      - 37
      4: 3.8.18
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
