program: train.py
name: dkt_sweep
description: dkt lstm sweep
project: level2-dkt
entity: boostcamp6-recsys6
method: bayes
metric:
  name: valid_auc_epoch
  goal: maximize
parameters:
  model:
    value: 'lstm'
  optimizer:
    values: ['adam', 'adamW']
  scheduler:
    values: ['plateau', 'linear_warmup']
  max_seq_len:
    min: 5
    max: 100
  lr:
    min: 0.000001
    max: 0.0001
  n_epochs:
    min: 10
    max: 30
  n_layers:
    min: 2
    max: 5
  n_heads:
    min: 2
    max: 5
  drop_out:
    min: 0.1
    max: 0.2
  hidden_dim:
    min: 32
    max: 128
  clip_grad:
    min: 5
    max: 20
  batch_size:
    min: 32
    max: 128
  patience:
    min: 5
    max: 10
  log_steps:
    value: 50
  new_num_feats:
    value: ['SolvingTime', 'same_tag_cumulative']