program: train.py
name: lastquery
description: lastquery model sweep
project: level2-lastquery
entity: boostcamp6-recsys6
method: bayes
metric:
  name: valid_auc_epoch
  goal: maximize
parameters:
  model:
    values: ['lastquery'] #, 'XG', 'LGBM']
  new_cat_feats:
    values: ["", "categorize_solvingTime categorize_TagAnswerRate categorize_ProblemAnswerRate categorize_TestAnswerRate",
     "categorize_solvingTime categorize_TagAnswerRate"]
  new_num_feats:
    values: ["", "CumulativeUserTagExponentialAverage CumulativeUserProblemAnswerRate", "CumulativeUserTagExponentialAverage TagAnswerRate"]
  n_choice:
    values: [5, 10]
  kfold:
    value: 5
  window:
    value: True
  max_seq_len:
    values: [20, 40, 80, 100, 1024]
  patience:
    value: 10
  n_epochs:
    value: 30
  lr:
    min: 0.000001
    max: 0.0001
  drop_out:
    values: [0.1, 0.2]