program: train.py
name: lastquery
description: lastquery model sweep
project: level2-lastquery
entity: boostcamp6-recsys6
method: bayes
metric:
  name: train_auc
  goal: maximize
parameters:
  model:
    values: ['lastquery'] #, 'XG', 'LGBM']
  new_cat_feats:
    values: ["", "categorize_solvingTime categorize_TagAnswerRate categorize_ProblemAnswerRate categorize_TestAnswerRate",
     "categorize_solvingTime categorize_TagAnswerRate"]
  new_num_feats:
    values: ["", "CumulativeUserTagExponentialAverage CumulativeUserProblemAnswerRate", "CumulativeUserTagExponentialAverage TagAnswerRate"]
  n_choice:
    values: [5, 10]
  kfold:
    value: 5
  window:
    value: True
  max_seq_len:
    values: [20, 30, 40, 50, 60, 80, 100]
  patience:
    value: 10
  n_epochs:
    value: 20