project: lightgbm-sweep
method: bayes

metric:
  name: auc
  goal: maximize

parameters:
  num_leaves:
    min: 10  # 미세 조정하지 않음
    max: 60  # 긍정적 상관관계가 있으므로 범위를 약간 늘림
  learning_rate:
    min: 0.0001  # 미세 조정하지 않음
    max: 0.7     # 긍정적 상관관계가 있으므로 범위를 약간 늘림
  min_data_in_leaf:
    min: 20   # 미세 조정하지 않음
    max: 120  # 약간 늘릴 수 있음
  feature_fraction:
    min: 0.5  # 중요도와 상관관계가 낮으므로 미세 조정
    max: 1.0  # 미세 조정하지 않음
  bagging_fraction:
    min: 0.5  # 중요도가 낮으므로 미세 조정
    max: 1.0  # 미세 조정하지 않음
  bagging_freq:
    min: 5    # 미세 조정하지 않음
    max: 30   # 높은 중요도와 긍정적 상관관계가 있으므로 범위를 늘림
  lambda_l1:
    min: 0.0  # 미세 조정하지 않음
    max: 15.0 # 중요도가 높으므로 범위를 약간 늘림
  lambda_l2:
    min: 0.0  # 미세 조정하지 않음
    max: 15.0 # 중요도가 높으므로 범위를
  max_depth:
    min: 10   # 미세 조정하지 않음
    max: 50   # 높은 중요도와 긍정적 상관관계가 있으므로 범위를 늘림
  ratio:
    min: 0.05
    max: 0.5