wandb_version: 1

bagging_fraction:
  desc: null
  value: 0.916428711306248
bagging_freq:
  desc: null
  value: 19
feature_fraction:
  desc: null
  value: 0.4239919795969231
lambda_l1:
  desc: null
  value: 6.750488430640479
lambda_l2:
  desc: null
  value: 7.062957645333093
learning_rate:
  desc: null
  value: 0.08945013133490491
max_depth:
  desc: null
  value: 44
min_data_in_leaf:
  desc: null
  value: 90
num_leaves:
  desc: null
  value: 41
ratio:
  desc: null
  value: 0.017015809743085208
project:
  desc: null
  value: lightgbm-sweep
method:
  desc: null
  value: bayes
metric:
  desc: null
  value:
  - auc
parameters:
  desc: null
  value:
    num_leaves:
      min: 25
      max: 60
    learning_rate:
      min: 0.001
      max: 0.2
    min_data_in_leaf:
      min: 80
      max: 120
    feature_fraction:
      min: 0.3
      max: 1.0
    bagging_fraction:
      min: 0.7
      max: 1.0
    bagging_freq:
      min: 5
      max: 20
    lambda_l1:
      min: 0.0
      max: 10.0
    lambda_l2:
      min: 0.0
      max: 15.0
    max_depth:
      min: 20
      max: 50
    ratio:
      min: 0.01
      max: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.2
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706172629.276189
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 53
      - 55
      3:
      - 2
      - 7
      - 16
      - 17
      - 23
      - 25
      - 37
      4: 3.8.18
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: training_auc
      6:
      - 3
      7:
      - 2
    - 1: valid_1_auc
      6:
      - 3
      7:
      - 2
objective:
  desc: null
  value: binary
device:
  desc: null
  value: cpu
num_iterations:
  desc: null
  value: 1500
early_stopping_round:
  desc: null
  value: null
