wandb_version: 1

seed:
  desc: null
  value: 42
use_cuda_if_available:
  desc: null
  value: true
data_dir:
  desc: null
  value: /data/ephemeral/home/data
output_dir:
  desc: null
  value: ./outputs/
hidden_dim:
  desc: null
  value: 64
n_layers:
  desc: null
  value: 1
alpha:
  desc: null
  value: null
n_epochs:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.001
model_dir:
  desc: null
  value: ./models/
model_name:
  desc: null
  value: best_model.pt
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704336612.308749
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
